version: '3'

services:

  web:
    volumes:
      - ./public:/var/www/html/public
      - ./var/log/nginx:/var/log/nginx
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  php:
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "1"
      DATABASE_URL: "mysql://docker:docker@mysqldb:3306/api-grandmother-recipes"
      PHP_ERROR_REPORTING: "E_ALL"
      PHP_DISPLAY_ERRORS: "On"
      PHP_DISPLAY_STARTUP_ERRORS: "On"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "docker"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      MYSQL_DATABASE: "api-grandmother-recipes"
