{{ if .Values.blue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-blue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
      slot: blue

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
        slot: blue
    spec:
      initContainers:
        - name: {{ .Release.Name }}-php
          image: "{{ .Values.image.php.repository }}:{{ .Values.image.php.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: api-public
              mountPath: /api_public
            - name: var-dir
              mountPath: /var_dir
          command:
            - bash
            - "-c"
            - |
              bin/console assets:install
              bin/console cache:warmup --env=prod
              cp -r /var/www/html/public/ /api_public/
              cp -r /var/www/html/var/ /var_dir/

      containers:
        # nginx
        - name: {{ .Release.Name }}-nginx-blue
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: app-config-volume
              mountPath: /etc/nginx/conf.d/php_upstream.conf
              subPath: php_upstream.conf
            - name: api-public
              mountPath: /var/www/html/public

        # php-fpm
        - name: {{ .Release.Name }}-php-blue
          image: "{{ .Values.image.php.repository }}:{{ .Values.image.php.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: fast-cgi
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: app-config-volume
              mountPath: /var/www/html/.env
              subPath: envs
            - name: var-dir
              mountPath: /var/www/html/var

      volumes:
        - name: app-config-volume
          configMap:
            name: {{ .Release.Name }}-config-map-blue
        - name: api-public
          emptyDir: {}
        - name: var-dir
          emptyDir: {}
{{ end }}