apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-stage
  labels:
    app: {{ .Release.Name }}
    env: prod
spec:
  type: {{ .Values.service.lb.type }}
  ports:
    - name: http
      port: {{ .Values.service.lb.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    {{- if eq .Values.productionSlot "blue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }}
