apiVersion: v1
kind: ConfigMap
metadata:
  name: capstone-config-map-blue
data:
    php_upstream.conf: |
      upstream php {
          server 127.0.0.1:9000;
      }
    envs: |
      APP_ENV=dev
      APP_DEBUG=1
      APP_SECRET=418b9bf2afef5ef40fd9f1b033b4b48d
      DATABASE_URL=mysql://user:pwd@127.0.0.1:3306/api-grandmother-recipes
      ENV_COLOR=blue