apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
      release: capstone
      slot: blue

  template:
    metadata:
      labels:
        app: capstone
        release: capstone
        slot: blue
    spec:
      initContainers:
        - name: capstone-php
          image: "davidasrocha/api-grandmother-recipes-php:latest"
          imagePullPolicy: Always
          volumeMounts:
            - name: api-public
              mountPath: /api_public
            - name: var-dir
              mountPath: /var_dir
          command:
            - bash
            - "-c"
            - |
              bin/console assets:install
              bin/console cache:warmup --env=prod
              cp -r /var/www/html/public/* /api_public/
              cp -r /var/www/html/var/* /var_dir/

      containers:
        # nginx
        - name: capstone-nginx-blue
          image: "davidasrocha/api-grandmother-recipes-nginx:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: app-config-volume
              mountPath: /etc/nginx/conf.d/php_upstream.conf
              subPath: php_upstream.conf
            - name: api-public
              mountPath: /var/www/html/public

        # php-fpm
        - name: capstone-php-blue
          image: "davidasrocha/api-grandmother-recipes-php:latest"
          imagePullPolicy: Always
          ports:
            - name: fast-cgi
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: app-config-volume
              mountPath: /var/www/html/.env
              subPath: envs
            - name: var-dir
              mountPath: /var/www/html/var

      volumes:
        - name: app-config-volume
          configMap:
            name: capstone-config-map-blue
        - name: api-public
          emptyDir: {}
        - name: var-dir
          emptyDir: {}