apiVersion: v1
kind: Service
metadata:
  name: capstone-service-prod
  labels:
    app: capstone
    env: prod
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: capstone
    release: capstone
    slot: blue
