blue:
  enabled: false

green:
  enabled: false

productionSlot: blue

replicaCount: 3

image:
  nginx:
    repository: davidasrocha/api-grandmother-recipes-nginx
    tag: stable
  php:
    repository: davidasrocha/api-grandmother-recipes-php
    tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: docker-registry-secret
nameOverride: ""
fullnameOverride: ""

service:
  lb:
    type: NodePort
    port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
